/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface InsuranceForm {
  'id' : bigint,
  'status' : Status,
  'insuranceType' : InsuranceType,
  'additionalDetails' : string,
  'country' : string,
  'beneficiaryName' : string,
  'dateOfBirth' : string,
  'city' : string,
  'submittedAt' : bigint,
  'email' : string,
  'zipCode' : string,
  'state' : string,
  'address' : string,
  'gender' : Gender,
  'coverageAmount' : number,
  'phone' : string,
  'lastName' : string,
  'startDate' : string,
  'firstName' : string,
}
export type InsuranceType = { 'life' : null } |
  { 'property' : null } |
  { 'vehicle' : null } |
  { 'health' : null };
export type Status = { 'pending' : null } |
  { 'reviewed' : null };
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<InsuranceForm>>,
  'getSubmissionById' : ActorMethod<[bigint], InsuranceForm>,
  'getTotalSubmissions' : ActorMethod<[], bigint>,
  'submitForm' : ActorMethod<
    [
      string,
      string,
      string,
      Gender,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      InsuranceType,
      number,
      string,
      string,
      string,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];