/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const InsuranceType = IDL.Variant({
  'life' : IDL.Null,
  'property' : IDL.Null,
  'vehicle' : IDL.Null,
  'health' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const InsuranceForm = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'insuranceType' : InsuranceType,
  'additionalDetails' : IDL.Text,
  'country' : IDL.Text,
  'beneficiaryName' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'city' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'coverageAmount' : IDL.Float64,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'startDate' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(InsuranceForm)], ['query']),
  'getSubmissionById' : IDL.Func([IDL.Nat], [InsuranceForm], ['query']),
  'getTotalSubmissions' : IDL.Func([], [IDL.Nat], ['query']),
  'submitForm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Gender,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        InsuranceType,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'pending' : IDL.Null, 'reviewed' : IDL.Null });
  const InsuranceType = IDL.Variant({
    'life' : IDL.Null,
    'property' : IDL.Null,
    'vehicle' : IDL.Null,
    'health' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const InsuranceForm = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'insuranceType' : InsuranceType,
    'additionalDetails' : IDL.Text,
    'country' : IDL.Text,
    'beneficiaryName' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'city' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'coverageAmount' : IDL.Float64,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'startDate' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(InsuranceForm)], ['query']),
    'getSubmissionById' : IDL.Func([IDL.Nat], [InsuranceForm], ['query']),
    'getTotalSubmissions' : IDL.Func([], [IDL.Nat], ['query']),
    'submitForm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Gender,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          InsuranceType,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };