/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InsuranceForm {
    id: bigint;
    status: Status;
    insuranceType: InsuranceType;
    additionalDetails: string;
    country: string;
    beneficiaryName: string;
    dateOfBirth: string;
    city: string;
    submittedAt: bigint;
    email: string;
    zipCode: string;
    state: string;
    address: string;
    gender: Gender;
    coverageAmount: number;
    phone: string;
    lastName: string;
    startDate: string;
    firstName: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum InsuranceType {
    life = "life",
    property = "property",
    vehicle = "vehicle",
    health = "health"
}
export enum Status {
    pending = "pending",
    reviewed = "reviewed"
}
export interface backendInterface {
    getAllSubmissions(): Promise<Array<InsuranceForm>>;
    getSubmissionById(id: bigint): Promise<InsuranceForm>;
    getTotalSubmissions(): Promise<bigint>;
    submitForm(firstName: string, lastName: string, dateOfBirth: string, gender: Gender, email: string, phone: string, address: string, city: string, state: string, zipCode: string, country: string, insuranceType: InsuranceType, coverageAmount: number, startDate: string, beneficiaryName: string, additionalDetails: string): Promise<bigint>;
}
import type { Gender as _Gender, InsuranceForm as _InsuranceForm, InsuranceType as _InsuranceType, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllSubmissions(): Promise<Array<InsuranceForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionById(arg0: bigint): Promise<InsuranceForm> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionById(arg0);
                return from_candid_InsuranceForm_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionById(arg0);
            return from_candid_InsuranceForm_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalSubmissions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSubmissions();
            return result;
        }
    }
    async submitForm(arg0: string, arg1: string, arg2: string, arg3: Gender, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: InsuranceType, arg12: number, arg13: string, arg14: string, arg15: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(arg0, arg1, arg2, to_candid_Gender_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_InsuranceType_n12(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14, arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(arg0, arg1, arg2, to_candid_Gender_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_InsuranceType_n12(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14, arg15);
            return result;
        }
    }
}
function from_candid_Gender_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceForm_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceForm): InsuranceForm {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceType): InsuranceType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    insuranceType: _InsuranceType;
    additionalDetails: string;
    country: string;
    beneficiaryName: string;
    dateOfBirth: string;
    city: string;
    submittedAt: bigint;
    email: string;
    zipCode: string;
    state: string;
    address: string;
    gender: _Gender;
    coverageAmount: number;
    phone: string;
    lastName: string;
    startDate: string;
    firstName: string;
}): {
    id: bigint;
    status: Status;
    insuranceType: InsuranceType;
    additionalDetails: string;
    country: string;
    beneficiaryName: string;
    dateOfBirth: string;
    city: string;
    submittedAt: bigint;
    email: string;
    zipCode: string;
    state: string;
    address: string;
    gender: Gender;
    coverageAmount: number;
    phone: string;
    lastName: string;
    startDate: string;
    firstName: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        insuranceType: from_candid_InsuranceType_n6(_uploadFile, _downloadFile, value.insuranceType),
        additionalDetails: value.additionalDetails,
        country: value.country,
        beneficiaryName: value.beneficiaryName,
        dateOfBirth: value.dateOfBirth,
        city: value.city,
        submittedAt: value.submittedAt,
        email: value.email,
        zipCode: value.zipCode,
        state: value.state,
        address: value.address,
        gender: from_candid_Gender_n8(_uploadFile, _downloadFile, value.gender),
        coverageAmount: value.coverageAmount,
        phone: value.phone,
        lastName: value.lastName,
        startDate: value.startDate,
        firstName: value.firstName
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    reviewed: null;
}): Status {
    return "pending" in value ? Status.pending : "reviewed" in value ? Status.reviewed : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    life: null;
} | {
    property: null;
} | {
    vehicle: null;
} | {
    health: null;
}): InsuranceType {
    return "life" in value ? InsuranceType.life : "property" in value ? InsuranceType.property : "vehicle" in value ? InsuranceType.vehicle : "health" in value ? InsuranceType.health : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceForm>): Array<InsuranceForm> {
    return value.map((x)=>from_candid_InsuranceForm_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_InsuranceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceType): _InsuranceType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceType): {
    life: null;
} | {
    property: null;
} | {
    vehicle: null;
} | {
    health: null;
} {
    return value == InsuranceType.life ? {
        life: null
    } : value == InsuranceType.property ? {
        property: null
    } : value == InsuranceType.vehicle ? {
        vehicle: null
    } : value == InsuranceType.health ? {
        health: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
